---
title: "{{< fa book-open >}} Resources"
---

### Primary Textbooks

These textbooks are great resources for some of the topics we will cover. 

 * Plane Answers to Complex Questions, Ronald Christensen.  [eBook in Duke Library](http://getitatduke.library.duke.edu/?sid=sersol&SS_jc=TC0000508493&title=Plane%20Answers%20to%20Complex%20Questions%3A%20The%20Theory%20of%20Linear%20Models)
 
* Linear Regression Analysis, George A.F Seber and  Alan J. Lee [eBook in Duke Library](https://find.library.duke.edu/catalog/DUKE003161269).  _Duke Library is aware the link is broken_

* The Linear Model and Hypothesis, George A. F. Seber [eBook in Duke Library](https://link-springer-com.proxy.lib.duke.edu/book/10.1007/978-3-319-21930-1)
 
### Supplementary Textbooks on Linear/Matrix  Algebra


* [Gilbert Strang's Online Course at MIT](http://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/index.htm)
* [Video Lectures](http://ocw.mit.edu/courses/mathematics/18-06-linear-algebra-spring-2010/video-lectures/)
  * Introduction to Linear Algebra. Strang, Gilbert. 4th ed. Wellesley, MA: Wellesley-Cambridge Press, 2009. ISBN: 9780980232714. [Buy @ Amazon](http://www.amazon.com/exec/obidos/ASIN/0980232716/ref=nosim/mitopencourse-20)

* Matrix Algebra from a Statistician's Perspective. Harville, David A. [eBook in Duke Library](http://getitatduke.library.duke.edu/?sid=sersol&SS_jc=TC0000199325&title=Matrix%20Algebra%20from%20a%20Statistician%27s%20Perspective)




### R and R Markdown Resources

Quarto/R Markdown/LaTeX can be used to create high quality reports and presentations with embedded chunks of R code and LaTeX equations! You are required to use Quarto in RStudio to type up your homework assignments that involve Data Analysis/Simulation for this course, but you are welcome to use any word processor of your choice for those. To learn more about Quarto/R Markdown and for other resources for programming in R, see the links below. 

* [Using R in Quarto for Documents](https://quarto.org/docs/computations/r.html)
* [R for Data Science (by Hadley Wickham & Garrett Grolemund)](https://r4ds.had.co.nz)
* [Introduction to R Markdown (Article by Garrett Grolemund)](https://rmarkdown.rstudio.com/articles_intro.html)
* [Introduction to R Markdown (Slides by Andrew Cho)](http://rpubs.com/andrew-cho/303981)
* [R Markdown Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf)
* [Data Visualization with ggplot2 Cheat Sheet](https://www.rstudio.com/wp-content/uploads/2016/11/ggplot2-cheatsheet-2.1.pdf)
* [Other Useful Cheat Sheets](https://www.rstudio.com/resources/cheatsheets/#import)
* [A very (very!) basic R Markdown template](https://sta-602l-s20.github.io/Course-Website/labs/resources/LabReport.Rmd)

### LaTeX

You may also use LaTeX to type up your assignments. You may find it easier to create your TeX and LaTeX documents using online editors such as [Overleaf](https://www.overleaf.com) (simply create a free account and you are good to go!). However, that need not be the case. If you prefer to create them locally/offline on your personal computers, you will need to download a TeX distribution (the most popular choices are [MiKTeX](https://miktex.org/download) for Windows and [MacTeX](http://www.tug.org/mactex/) for macOS) plus an editor (I personally prefer [TeXstudio](https://www.texstudio.org) but feel free to download any editor of your choice). Follow the links below for some options, and to also learn how to use LaTeX.

1. [Learn LaTeX in 30 minutes](https://www.overleaf.com/learn/latex/Learn_LaTeX_in_30_minutes)
2. [Choosing a LaTeX Compiler](https://www.overleaf.com/learn/latex/Choosing_a_LaTeX_Compiler).

### Interesting Articles

I will add articles I find interesting below. These are articles I find useful as supplementary readings for topics covered in class, or as good sources that cover concepts I think you should know, but which we may not have time to cover. I strongly suggest you find time to (at the very least) take a "quick peek" at each article.

1. Efron, B., 1986. Why isn't everyone a Bayesian?. The American Statistician, 40(1), pp. 1-5.
2. Gelman, A., 2008. Objections to Bayesian statistics. Bayesian Analysis, 3(3), pp. 445-449.
3. Diaconis, P., 1977. Finite forms of de Finetti's theorem on exchangeability. Synthese, 36(2), pp. 271-281.
4. Gelman, A., Meng, X. L. and Stern, H., 1996. Posterior predictive assessment of model fitness via realized discrepancies. Statistica sinica, pp. 733-760.
5. Dunson, D. B., 2018. Statistics in the big data era: Failures of the machine. Statistics & Probability Letters, 136, pp. 4-9.